# Generated by Django 3.2.14 on 2022-08-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo documento',
                'verbose_name_plural': 'tipo de documento',
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Empresa evaluadora',
                'verbose_name_plural': 'Empresas evaluadoras',
                'db_table': 'evaluation_company',
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de evaluacion',
                'verbose_name_plural': 'tipo de evaluaciones',
                'db_table': 'evaluation_type',
            },
        ),
        migrations.CreateModel(
            name='PositionApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'cargo a postular',
                'verbose_name_plural': 'cargos a postular',
                'db_table': 'position_apply',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': 'status',
            },
        ),
    ]
