# Generated by Django 3.2.14 on 2022-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_evaluationclinical_exammedicaltype_personainterviewlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado civil',
                'verbose_name_plural': 'Estados civil',
                'db_table': 'civil_status',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'deparments',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provinces',
            },
        ),
    ]
