# Generated by Django 3.2.14 on 2022-08-02 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default=1, help_text='celular', max_length=100, verbose_name='celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(db_column='usu_reg', default=1, help_text='usuario registrado', max_length=100, verbose_name='usuario registrado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='fec_reg', default=django.utils.timezone.now, help_text='fecha registro', verbose_name='fecha registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, help_text='telefono', max_length=100, verbose_name='telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='update_by',
            field=models.CharField(db_column='usu_edicion', default=1, help_text='usuario edicion', max_length=100, verbose_name='usuario edicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='rol'),
        ),
    ]
