# Generated by Django 3.2.14 on 2022-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, default=None, help_text='celular', max_length=100, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, help_text='telefono', max_length=100, null=True, verbose_name='telefono'),
        ),
    ]
