# Generated by Django 3.2.14 on 2022-08-03 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('name', models.CharField(db_column='nombre', help_text='Nombre', max_length=100, verbose_name='nombre')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Verificacion'), (2, 'Entrevista personal'), (3, 'Fuera del proceso'), (3, 'Examen medico')], default=1, null=True, verbose_name='Estado del postulante')),
                ('last_name', models.CharField(blank=True, default=None, help_text='Primer apellido', max_length=100, null=True, verbose_name='primer apellido')),
                ('sur_name', models.CharField(blank=True, default=None, help_text='Segundo apellido', max_length=100, null=True, verbose_name='segundo apellido')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='email address')),
                ('application_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha poatulacion')),
            ],
            options={
                'verbose_name': 'postulante',
                'verbose_name_plural': 'postulantes',
                'db_table': 'postulants',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('speciality', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='especialidad')),
                ('company', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='empresa')),
                ('init_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha fin')),
                ('postulant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision.postulant')),
            ],
            options={
                'verbose_name': 'experiencia laboral',
                'verbose_name_plural': 'experiencia laboral',
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Titulo de la oferta')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripcion de la oferta')),
                ('requisito', models.TextField(blank=True, default=None, null=True, verbose_name='Requisitos de la oferta')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'Aprobada'), (3, 'Rechazada')], default=1, null=True, verbose_name='Estado de la oferta')),
                ('deactivation_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Desactivacion de la oferta')),
                ('publication_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Publicacion de la oferta')),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.positionapply')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Programado'), (2, 'Aprobado'), (3, 'Cancelado'), (4, 'Desaprobado')], default=1, null=True, verbose_name='Estado de la evaluacion')),
                ('observations', models.TextField(blank=True, default=None, null=True, verbose_name='Observaciones del postulante')),
                ('programed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha programada')),
                ('assigned', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evaluation_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.evaluationcompany')),
                ('evaluation_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.evaluationtype')),
                ('postulant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision.postulant')),
            ],
            options={
                'verbose_name': 'evaluacion',
                'verbose_name_plural': 'evaluaciones',
                'db_table': 'evaluations',
            },
        ),
    ]
