# Generated by Django 3.2.14 on 2022-08-03 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_evaluationclinical_exammedicaltype_personainterviewlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='is_medical_exam',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='examen medico?'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='is_personal_interview',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='entrevista personal?'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='assigned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='postulant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulant_evaluations', to='admision.postulant'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='application_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha postulacion'),
        ),
        migrations.CreateModel(
            name='PersonalInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Programado'), (2, 'Aprobado'), (3, 'Cancelado'), (4, 'Desaprobado')], default=1, null=True, verbose_name='Estado de la evaluacion')),
                ('programed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha programada')),
                ('observations', models.TextField(blank=True, default=None, null=True, verbose_name='Observaciones del postulante')),
                ('assigned', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_personalinterviews', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.personainterviewlocation')),
                ('postulant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulant_personalinterviews', to='admision.postulant')),
            ],
            options={
                'verbose_name': 'entrevista personal',
                'verbose_name_plural': 'entrevistas personales',
                'db_table': 'personal_interview',
            },
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='estado', default=True, help_text='estado', verbose_name='estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='fec_reg', help_text='fecha registro', verbose_name='fecha registro')),
                ('created_by', models.CharField(db_column='usu_reg', help_text='usuario registrado', max_length=100, verbose_name='usuario registrado')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='fec_edicion', help_text='fecha edicion', verbose_name='fecha edicion')),
                ('update_by', models.CharField(db_column='usu_edicion', help_text='usuario edicion', max_length=100, verbose_name='usuario edicion')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Programado'), (2, 'Aprobado'), (3, 'Cancelado'), (4, 'Desaprobado')], default=1, null=True, verbose_name='Estado de la evaluacion')),
                ('programed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha programada')),
                ('observations', models.TextField(blank=True, default=None, null=True, verbose_name='Observaciones del postulante')),
                ('assigned', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_medicalexams', to=settings.AUTH_USER_MODEL)),
                ('clinical', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.evaluationclinical')),
                ('exam_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.exammedicaltype')),
                ('postulant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulant_medicalexams', to='admision.postulant')),
            ],
            options={
                'verbose_name': 'examen medico',
                'verbose_name_plural': 'examenes medicos',
                'db_table': 'medical_exams',
            },
        ),
    ]
