# Generated by Django 3.2.14 on 2022-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_offer_offer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='fecha publicada', verbose_name='Publicacion de la oferta'),
            preserve_default=False,
        ),
    ]
