# Generated by Django 3.2.14 on 2022-08-07 17:27

from django.db import migrations, models
import django.db.models.deletion
import ttk_backend.apps.admision.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_civilstatus_department_district_province'),
        ('admision', '0004_alter_offer_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='address',
            field=models.CharField(blank=True, default=None, help_text='Direccion', max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='cellphone',
            field=models.CharField(blank=True, default=None, help_text='celular', max_length=100, null=True, verbose_name='celular'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='civil_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.civilstatus'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='curriculum_file',
            field=models.FileField(default=None, help_text='Curriculum File.', null=True, upload_to=ttk_backend.apps.admision.models.Postulant.curricumlum_doc_file_path, verbose_name='curriculum'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='document_file',
            field=models.FileField(default=None, help_text='Document File.', null=True, upload_to=ttk_backend.apps.admision.models.Postulant.documents_doc_file_path, verbose_name='document file'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='document_number',
            field=models.CharField(blank=True, default=None, help_text='Document number', max_length=100, null=True, verbose_name='document number'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='image_file',
            field=models.ImageField(default=None, help_text='image File.', null=True, upload_to=ttk_backend.apps.admision.models.Postulant.image_file_path, verbose_name='image file'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='is_experience',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='experiencia?'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='is_travel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='disponibilidad para viajar?'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='phone',
            field=models.CharField(blank=True, default=None, help_text='telefono', max_length=100, null=True, verbose_name='telefono'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='profesion_company',
            field=models.CharField(blank=True, default=None, help_text='profesion - empresa', max_length=100, null=True, verbose_name='profesion - empresa'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='profesion_last_course',
            field=models.CharField(blank=True, default=None, help_text='profesion - ultimo curso realizado', max_length=100, null=True, verbose_name='profesion - ultimo curso realizado'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='profesion_location',
            field=models.CharField(blank=True, default=None, help_text='lugar de profesion', max_length=100, null=True, verbose_name='lugar de profesion'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='profession_description',
            field=models.CharField(blank=True, default=None, help_text='profesion', max_length=100, null=True, verbose_name='profesion'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='secondary_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='secondary email address'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='work_company',
            field=models.CharField(blank=True, default=None, help_text='Empresa de trabajo', max_length=100, null=True, verbose_name='Empresa de trabajo'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='work_description',
            field=models.CharField(blank=True, default=None, help_text='Trabajo mas reciente', max_length=100, null=True, verbose_name='Trabajo mas reciente'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='work_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='work_exit_description',
            field=models.CharField(blank=True, default=None, help_text='Motivo de salida de trabajo', max_length=100, null=True, verbose_name='Motivo de salida de trabajo'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='work_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
