# Generated by Django 3.2.14 on 2022-08-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0005_auto_20220807_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='second_name',
            field=models.CharField(blank=True, default=None, help_text='segundo nombre', max_length=100, null=True, verbose_name='segundo nombre'),
        ),
    ]
