# Generated by Django 3.2.14 on 2022-08-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_civilstatus_department_district_province'),
        ('admision', '0006_postulant_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.department'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.province'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='second_cellphone',
            field=models.CharField(blank=True, default=None, help_text='segundo celular', max_length=100, null=True, verbose_name='segundo celular'),
        ),
    ]
